language: rust
rust:
  - nightly

before_install:
  - sudo apt-get -y install qemu-system-x86
  # https://github.com/rust-osdev/bootimage/issues/64
  - (cd .. && cargo install bootimage)
  - rustup component add rust-src llvm-tools-preview

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
