[package]
name = "os"
version = "0.1.0"
authors = ["Luc Street <lucis-fluxum@users.noreply.github.com>"]
edition = "2018"

[package.metadata.bootimage]
test-args = [
    "-device", "isa-debug-exit,iobase=0xf4,iosize=0x04",
    "-serial", "stdio", 
    "-display", "none"
]
test-success-exit-code = 33 # Since (0x10 << 1) | 1 = 33
test-timeout = 300

[dependencies]
bootloader = "0.9.4"
conquer-once = { version = "0.2.0", default-features = false }
log = "0.4.8"
pc-keyboard = "0.5.0"
pic8259_simple = "0.2.0"
spinning_top = "0.1.0"
uart_16550 = "0.2.7"
volatile = "0.2.6"
x86_64 = "0.11.0"

[[test]]
name = "should_panic"
harness = false

[[test]]
name = "stack_overflow"
harness = false
